# Generated by Django 4.2.11 on 2024-03-31 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('categoria', models.CharField(choices=[('director', 'Director'), ('reserva', 'Reserva'), ('cuadro', 'Cuadro'), ('tecnico', 'Técnico')], max_length=20, verbose_name='Categoría')),
                ('stock', models.IntegerField(verbose_name='Cantidad en stock')),
            ],
        ),
    ]
