# Generated by Django 4.2.11 on 2024-04-01 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermercado_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('fresco', 'Fresco'), ('bebidas', 'Bebidas'), ('congelados', 'Congelados'), ('abarrotes', 'Abarrotes'), ('panaderia', 'Panadería'), ('limpieza', 'Limpieza'), ('higiene_personal', 'Higiene Personal'), ('cuidado_hogar', 'Cuidado del Hogar'), ('electronica', 'Electrónicos'), ('snacks', 'Snacks')], max_length=20, verbose_name='Categoría'),
        ),
    ]
