# Generated by Django 4.2.11 on 2024-04-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermercado_app', '0002_alter_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('alimentos', 'Alimentos'), ('snacks', 'Snacks'), ('bebidas', 'bebidas'), ('ropa', 'Ropa'), ('zapatos', 'Zapatos'), ('maquillaje', 'Maquillaje'), ('deportes', 'Deportes'), ('electrodomesticos', 'Electrodomésticos'), ('limpieza', 'Limpieza'), ('higiene_personal', 'Higiene Personal'), ('cuidado_hogar', 'Cuidado del Hogar'), ('tecnolgia', 'Tecnología')], max_length=20, verbose_name='Categoría'),
        ),
    ]
